"""Isolated production foundations for bounded health-history storage.

This package is intentionally not imported by a current runtime entry point.
"""

from aurora_core.health_history.ingestion import (
    IngestionError,
    IngestionOutcome,
    IngestionRejection,
    IngestionResult,
)
from aurora_core.health_history.maintenance import (
    DEFAULT_RETENTION_DAYS,
    INCREMENTAL_VACUUM_PAGES,
    MAX_RETENTION_DAYS,
    MIN_RETENTION_DAYS,
    RETENTION_ROW_BUDGET,
    IncrementalVacuumResult,
    MaintenanceError,
    MaintenanceOutcome,
    MaintenanceRejection,
    RetentionCleanupResult,
)
from aurora_core.health_history.models import (
    AlertKind,
    AlertLifecycle,
    AlertScope,
    ComponentName,
    HealthHistoryStatus,
    LifecycleEvent,
    SampleKind,
    SamplingGapPhase,
)
from aurora_core.health_history.projection import (
    ComponentProjection,
    HealthProjection,
    ProjectionError,
    ProjectionRejection,
    project_health_report,
    validate_health_projection,
)
from aurora_core.health_history.queries import (
    DEFAULT_ALERT_EVENT_PAGE_SIZE,
    DEFAULT_ALERT_PAGE_SIZE,
    DEFAULT_HEALTH_SAMPLE_PAGE_SIZE,
    MAX_ALERT_EVENT_PAGE_SIZE,
    MAX_ALERT_PAGE_SIZE,
    MAX_HEALTH_SAMPLE_PAGE_SIZE,
    AlertCursor,
    AlertEventCursor,
    AlertEventPage,
    AlertEventRecord,
    AlertPage,
    AlertRecord,
    HealthComponentRecord,
    HealthSampleCursor,
    HealthSamplePage,
    HealthSampleRecord,
    QueryError,
    QueryRejection,
)
from aurora_core.health_history.store import HealthHistoryStore

__all__ = [
    "AlertKind",
    "AlertLifecycle",
    "AlertCursor",
    "AlertEventCursor",
    "AlertEventPage",
    "AlertEventRecord",
    "AlertPage",
    "AlertRecord",
    "AlertScope",
    "ComponentName",
    "ComponentProjection",
    "DEFAULT_ALERT_EVENT_PAGE_SIZE",
    "DEFAULT_ALERT_PAGE_SIZE",
    "DEFAULT_HEALTH_SAMPLE_PAGE_SIZE",
    "DEFAULT_RETENTION_DAYS",
    "HealthComponentRecord",
    "HealthHistoryStatus",
    "HealthHistoryStore",
    "HealthProjection",
    "HealthSampleCursor",
    "HealthSamplePage",
    "HealthSampleRecord",
    "IngestionError",
    "IngestionOutcome",
    "IngestionRejection",
    "IngestionResult",
    "IncrementalVacuumResult",
    "INCREMENTAL_VACUUM_PAGES",
    "LifecycleEvent",
    "MAX_ALERT_EVENT_PAGE_SIZE",
    "MAX_ALERT_PAGE_SIZE",
    "MAX_HEALTH_SAMPLE_PAGE_SIZE",
    "MAX_RETENTION_DAYS",
    "MIN_RETENTION_DAYS",
    "MaintenanceError",
    "MaintenanceOutcome",
    "MaintenanceRejection",
    "ProjectionError",
    "ProjectionRejection",
    "QueryError",
    "QueryRejection",
    "RETENTION_ROW_BUDGET",
    "RetentionCleanupResult",
    "SampleKind",
    "SamplingGapPhase",
    "project_health_report",
    "validate_health_projection",
]
